import mongoose from "mongoose"

const { Schema } = mongoose

const phonePeTransactionSchema = new Schema(
  {
    userId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    // Generated by OUR backend, unique per attempt. This is what we send to PhonePe.
    merchantOrderId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    // PhonePe's own orderId (e.g. "OMO...") returned from the Create Order call.
    phonepeOrderId: {
      type: String,
    },
    amount: {
      type: Number, // rupees, what we show the user / credit to wallet
      required: true,
    },
    amountInPaise: {
      type: Number, // what PhonePe actually receives (amount * 100)
      required: true,
    },
    status: {
      type: String,
      enum: ["PENDING", "COMPLETED", "FAILED", "CANCELLED"],
      default: "PENDING",
      index: true,
    },
    paymentMode: {
      type: String, // UPI, CARD, NETBANKING, etc — filled in once known
    },
    // Idempotency guard: wallet must be credited exactly once per transaction,
    // no matter how many times webhook/verify fire for the same order.
    walletCredited: {
      type: Boolean,
      default: false,
    },
    errorCode: {
      type: String,
    },
    // Full last-known raw payload from PhonePe (create order / status / webhook)
    // kept for audit + debugging disputes.
    rawStatusResponse: {
      type: Schema.Types.Mixed,
    },
    environment: {
      type: String,
      enum: ["SANDBOX", "PRODUCTION"],
      default: () =>
        process.env.PHONEPE_ENV === "PRODUCTION" ? "PRODUCTION" : "SANDBOX",
    },
  },
  {
    timestamps: true,
  },
)

const PhonePeTransaction = mongoose.model(
  "PhonePeTransaction",
  phonePeTransactionSchema,
)

export default PhonePeTransaction
